name: Terraform Managed AKS
description: Provision an Azure Kubernetes Service using Terraform
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - prod
      action:
        description: "Action to perform"
        required: true
        default: "create"
        type: choice
        options:
          - create
          - destroy

  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      action:
        required: false
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      GH_PAT:
        required: true
        description: "GitHub Personal Access Token with repo scope"
jobs:
  smoketest:
    uses: ./.github/workflows/smoketest.yml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}    
  iac:
    name: ${{ github.event.inputs.action }} ${{ github.event.inputs.environment }} environment
    if: github.ref == 'refs/heads/main'
    needs: smoketest
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        working-directory: aks-${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: sianob/bp-iac
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ secrets.GH_PAT }} # Needed to access private repos

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Create Plan
        if: github.event.inputs.action == 'create'
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan > plan.out
      
      - name: Terraform Destroy Plan
        if: github.event.inputs.action == 'destroy'
        run: terraform plan -destroy -var-file="terraform.tfvars" -out=tfplan > plan.out

      - name: Check for Changes
        id: changes
        run: |
          if grep -q "Your infrastructure matches the configuration" plan.out || grep -q "No objects need to be destroyed"; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: github.event.inputs.action == 'create' && steps.changes.outputs.no_changes == 'false'
        run: |
          terraform apply -auto-approve -var-file="terraform.tfvars"

      - name: Install or upgrade Ingress NGINX via Helm
        if: github.event.inputs.action == 'create'
        run: |
          terraform output -raw kubeconfig >./aks-config
          cat ./aks-config
          export KUBECONFIG=./aks-config
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --create-namespace \
            --namespace ingress-nginx \
            --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
            --set controller.service.externalTrafficPolicy=Local

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy' && steps.changes.outputs.no_changes == 'false'
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_PAT }}"

      - name: Store Kubeconfig as secret for deploy - ${{ github.event.inputs.environment }}
        if: github.event.inputs.action == 'create'
        run: |
          ENV_NAME=${{ github.event.inputs.environment }}
          SECRET_NAME="KUBECONFIG_${ENV_NAME^^}"  # Bash uppercase
          echo "Setting secret $SECRET_NAME"
          gh secret set "$SECRET_NAME" \
            --repo sianob/bp-deploy \
            --body "$(terraform output -raw kubeconfig)"
        
      - name: Delete Kubeconfig secret for deploy - ${{ github.event.inputs.environment }}
        if: github.event.inputs.action == 'destroy' && steps.changes.outputs.no_changes == 'false'
        run: |
          ENV_NAME=${{ github.event.inputs.environment }}
          SECRET_NAME="KUBECONFIG_${ENV_NAME^^}"  # Bash uppercase
          echo "Deleting secret $SECRET_NAME"
          gh secret delete "$SECRET_NAME" \
          --repo sianob/bp-deploy
